		LXI H,0005H
		SHLD 1000H
		SHLD 1008H			;COPY OF DIVIDEND STORED. FACILITATES IN DIV. CONTROL
		LXI H,0001H
		SHLD 1002H

		;LOAD DIVISOR TO REG
		LHLD 1002H
		MOV A,L				;1'S COMPLEMENT OF LOW BYTE
		CMA
		ADI 01H				;2'S COMPLEMENT OF LOW BYTE
		MOV C,A
		MOV A,H
		CMA
		ACI 00H
		MOV B,A				;2'S COMPLEMENT OF HIGH BYTE
							;STORE DIVISOR AT LOCATION 1004H
		LXI H,1004H
		MOV M,C
		LXI H,1005H
		MOV M,B
		
		;LOAD DIVIDEND TO REG
		LHLD 1000H
		
		;LOAD QUOTIENT TO REGISTER
QUOTIENT_LOAD:
		LXI D, 0000H
	
DIVIDEND_CHECK:
		LHLD 1002H
		MOV B,H
		MOV C,L
		LDA 1009H
		CMP B
		JM STORE_Q_AND_R
		
		LDA 1008H
		CMP C
		JM STORE_Q_AND_R
		
DIVISION_BY_ADDITION:
		LHLD 1004H
		MOV B,H
		MOV C,L
		LHLD 1008H
		DAD B
		INX D
		SHLD 1008H
		JMP DIVIDEND_CHECK
		
STORE_Q_AND_R:
		SHLD 1008H		;STORE REMAINDER
		XCHG
		SHLD 1006H		;STORE QUOTIENT
		HLT